"use client";

import { useState, useEffect } from "react";
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend
} from "recharts";
import { TrendingDown, TrendingUp, Info, Activity, Percent, ArrowDownRight, ArrowUpRight } from "lucide-react";

// Mock Data
const CATEGORY_TRENDS_DATA = [
  { month: "Jan", Laptops: 152000, Smartphones: 112000, Televisions: 78000 },
  { month: "Feb", Laptops: 149000, Smartphones: 109000, Televisions: 78500 },
  { month: "Mar", Laptops: 145000, Smartphones: 113000, Televisions: 75000 },
  { month: "Apr", Laptops: 144500, Smartphones: 110000, Televisions: 72000 },
  { month: "May", Laptops: 139999, Smartphones: 114000, Televisions: 71500 },
  { month: "Jun", Laptops: 139999, Smartphones: 111000, Televisions: 68500 },
];

const DEFAULT_INDEX_DATA = [
  { month: "Jan", index: 100 },
  { month: "Feb", index: 101.4 },
  { month: "Mar", index: 102.8 },
  { month: "Apr", index: 101.9 },
  { month: "May", index: 102.5 },
  { month: "Jun", index: 101.8 },
];

const DEFAULT_INFLATION_DATA = [
  { month: "Jan", rate: 0.8 },
  { month: "Feb", rate: 1.4 },
  { month: "Mar", rate: 1.3 },
  { month: "Apr", rate: -0.9 },
  { month: "May", rate: 0.6 },
  { month: "Jun", rate: -0.7 },
];

export default function PriceIndexPage() {
  const [indexData, setIndexData] = useState(DEFAULT_INDEX_DATA);
  const [inflationData, setInflationData] = useState(DEFAULT_INFLATION_DATA);

  useEffect(() => {
    fetch("/api/price-index")
      .then((res) => res.json())
      .then((data) => {
        if (Array.isArray(data) && data.length > 0) {
          const monthOrder = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"];
          const sorted = [...data].sort(
            (a, b) => monthOrder.indexOf(a.month) - monthOrder.indexOf(b.month)
          );
          setIndexData(sorted);

          const computedInflation = sorted.map((item, idx) => {
            if (idx === 0) return { month: item.month, rate: 0.8 };
            const prev = sorted[idx - 1].index;
            const rate = Number((((item.index - prev) / prev) * 100).toFixed(1));
            return { month: item.month, rate };
          });
          setInflationData(computedInflation);
        }
      })
      .catch((err) => console.error("Failed to load price index:", err));
  }, []);

  const latestIndex = indexData[indexData.length - 1]?.index || 101.8;
  const latestInflation = inflationData[inflationData.length - 1]?.rate || -0.7;

  return (
    <div className="container mx-auto px-4 py-10 space-y-10">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-extrabold tracking-tight text-foreground">Monthly Consumer Price Index</h1>
        <p className="text-muted-foreground text-xs sm:text-sm mt-1">
          Dynamic online retail inflation metrics across e-commerce categories in Nepal, generated by analyzing 50,000+ assets daily.
        </p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          {
            title: "Online Price Index (DPI)",
            val: latestIndex.toString(),
            desc: "Base 100 in January 2026",
            icon: Activity,
            trend: latestInflation < 0 ? "down" : "up",
            trendVal: `${Math.abs(latestInflation)}% MoM`,
          },
          {
            title: "MoM Inflation Indicator",
            val: `${latestInflation}%`,
            desc: latestInflation < 0 ? "Deflation trend detected" : "Inflation trend detected",
            icon: Percent,
            trend: latestInflation < 0 ? "down" : "up",
            trendVal: `${Math.abs(latestInflation)}% ${latestInflation < 0 ? "decline" : "increase"}`,
          },
          {
            title: "YoY E-commerce Deflation",
            val: "-3.2%",
            desc: "Year over year net change",
            icon: TrendingDown,
            trend: "down",
            trendVal: "Declining",
          },
          {
            title: "Max Price Volatility Sector",
            val: "Laptops",
            desc: "Tech gadgets dropped most",
            icon: TrendingUp,
            trend: "up",
            trendVal: "8.2% drop",
          },
        ].map((stat, idx) => (
          <div key={idx} className="bg-card border border-border p-5 rounded-2xl shadow-sm flex flex-col justify-between space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs text-muted-foreground font-semibold">{stat.title}</span>
              <div className="p-2 rounded-lg bg-muted text-muted-foreground">
                <stat.icon className="h-4 w-4" />
              </div>
            </div>

            <div className="space-y-1">
              <p className="text-2xl font-bold text-foreground">{stat.val}</p>
              <div className="flex items-center justify-between text-[10px] font-bold">
                <span className="text-muted-foreground">{stat.desc}</span>
                <span className={`px-2 py-0.5 rounded-full flex items-center gap-0.5 ${stat.trend === "down" ? "bg-success/10 text-success" : "bg-primary/10 text-primary"
                  }`}>
                  {stat.trend === "down" ? <ArrowDownRight className="h-3 w-3" /> : <ArrowUpRight className="h-3 w-3" />}
                  <span>{stat.trendVal}</span>
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Category Price Trends */}
        <div className="bg-card border border-border p-6 rounded-2xl shadow-sm space-y-4">
          <div>
            <h3 className="font-bold text-foreground">Category Price Trends (Avg NPR)</h3>
            <p className="text-xs text-muted-foreground">Average price curves of major sectors over 6 months</p>
          </div>

          <div className="h-72 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={CATEGORY_TRENDS_DATA}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" opacity={0.5} />
                <XAxis dataKey="month" stroke="#9ca3af" fontSize={10} tickLine={false} />
                <YAxis stroke="#9ca3af" fontSize={10} tickLine={false} />
                <Tooltip contentStyle={{ backgroundColor: "var(--card)", borderColor: "var(--border)", borderRadius: "12px", fontSize: "11px" }} />
                <Legend wrapperStyle={{ fontSize: "11px" }} />
                <Area type="monotone" dataKey="Laptops" stroke="#2563EB" fill="#2563EB" fillOpacity={0.05} strokeWidth={2} />
                <Area type="monotone" dataKey="Smartphones" stroke="#0EA5E9" fill="#0EA5E9" fillOpacity={0.05} strokeWidth={2} />
                <Area type="monotone" dataKey="Televisions" stroke="#10B981" fill="#10B981" fillOpacity={0.05} strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Monthly General Index */}
        <div className="bg-card border border-border p-6 rounded-2xl shadow-sm space-y-4">
          <div>
            <h3 className="font-bold text-foreground">Monthly DPI Level</h3>
            <p className="text-xs text-muted-foreground">General online price index level (base 100 in Jan)</p>
          </div>

          <div className="h-72 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={indexData}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" opacity={0.5} />
                <XAxis dataKey="month" stroke="#9ca3af" fontSize={10} tickLine={false} />
                <YAxis stroke="#9ca3af" fontSize={10} domain={['dataMin - 2', 'auto']} tickLine={false} />
                <Tooltip contentStyle={{ backgroundColor: "var(--card)", borderColor: "var(--border)", borderRadius: "12px", fontSize: "11px" }} />
                <Bar dataKey="index" fill="#2563EB" radius={[4, 4, 0, 0]} barSize={28} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Inflation/Deflation Indicators */}
        <div className="bg-card border border-border p-6 rounded-2xl shadow-sm space-y-4 lg:col-span-2">
          <div>
            <h3 className="font-bold text-foreground">Month-on-Month Inflation Indicators (%)</h3>
            <p className="text-xs text-muted-foreground">Rate of price changes vs preceding month</p>
          </div>

          <div className="h-72 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={inflationData}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" opacity={0.5} />
                <XAxis dataKey="month" stroke="#9ca3af" fontSize={10} tickLine={false} />
                <YAxis stroke="#9ca3af" fontSize={10} tickLine={false} />
                <Tooltip contentStyle={{ backgroundColor: "var(--card)", borderColor: "var(--border)", borderRadius: "12px", fontSize: "11px" }} />
                <Line type="monotone" dataKey="rate" stroke="#ef4444" strokeWidth={2.5} dot={{ r: 4 }} activeDot={{ r: 6 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Explanatory Banner */}
      <div className="p-5 bg-muted/40 border border-border rounded-2xl flex items-start gap-4 text-xs leading-relaxed text-muted-foreground">
        <Info className="h-5 w-5 text-primary shrink-0 mt-0.5" />
        <div className="space-y-1">
          <h5 className="font-bold text-foreground">Methodology Note</h5>
          <p>
            The Dealert Price Index (DPI) aggregates pricing variations from 40+ Nepalese online catalogs (tech stores, department stores, book stores, fashion houses). Category weights are computed using approximate local transaction volumes in Nepal e-commerce. Index reports are generated on the 1st day of every month.
          </p>
        </div>
      </div>
    </div>
  );
}
